basePath: /
definitions:
  handlers.CalculateRequest:
    properties:
      order:
        example: 501
        minimum: 0
        type: integer
      pack_sizes:
        example:
        - 250
        - 500
        - 1000
        - 2000
        - 5000
        items:
          type: integer
        type: array
    type: object
  handlers.CalculateResponse:
    properties:
      order:
        example: 501
        type: integer
      pack_sizes:
        example:
        - 250
        - 500
        - 1000
        - 2000
        - 5000
        items:
          type: integer
        type: array
      packs:
        additionalProperties:
          type: integer
        example:
          "250": 1
          "500": 1
        type: object
      surplus:
        example: 249
        type: integer
      total_items:
        example: 750
        type: integer
      total_packs:
        example: 2
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: luisfernandomoraes@example.com
    name: Luis Fernando Moraes
  description: A REST API to calculate the optimal package combination to fulfill
    orders, minimizing items shipped and number of packages.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Order Packing Calculator API
  version: "1.0"
paths:
  /api/calculate:
    post:
      consumes:
      - application/json
      description: Calculates the best package combination to fulfill an order, minimizing
        items shipped and number of packages
      parameters:
      - description: Order quantity and package sizes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CalculateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.CalculateResponse'
        "400":
          description: Bad Request - Invalid order, negative value, or invalid pack
            sizes
          schema:
            additionalProperties:
              type: string
            type: object
        "405":
          description: Method Not Allowed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Calculate optimal package combination
      tags:
      - calculate
  /health:
    get:
      description: Returns the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: 'status: healthy'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check endpoint
      tags:
      - health
schemes:
- http
- https
swagger: "2.0"
